use memestash;

insert into cards(name, picture, price, description)
values ('Hank Hill Listens to X', null, 100,
        'Hank Hill Listens to X is a series of YouTube videos showing Hank Hill from the animated TV series King of the Hill listening to music on headphones, reacting with a horrified and baffled expression. The original clip comes from the first episode of the series, broadcast January 12th, 1997.'),
       ('Megalovania', null, 300,
        '"Megalovania" is a song composed by musician and video game developer Toby "Radiation" Fox. The song, featured on Fox\'s Earthbound Halloween Hack and the webcomic series Homestuck, experienced a rise of popularity after the release of the video game Undertale in September 2015, inspiring remixes and mash-ups.In 2008, Toby Fox released the EarthBound Halloween Hack,[1] a ROM hack of the SNES video game Earthbound. During the final boss fight against Dr. Andonuts, a track produced for the game titled "Megalovania" plays. On December 5th, 2009, YouTuber[6] Cameron uploaded the song, garnering over 2.6 million views in 12 years.'),
       ('A weapon to Surpass Metal Gear', null, 200,
        'A Weapon to Surpass Metal Gear" is a memorable quote from the 2015 video game Metal Gear Solid V: The Phantom Pain, which became a popular catchphrase and copypasta after the release of the game''s extended trailer at E3 2013. The phrase is often used alongside images and videos of abnormal machinery or weapons, much like the tacticool format, implying the machinery shown could take on a "Metal Gear." Videos referencing the phrase often contain the songs "Sins of The Father" or "Nuclear".'),
       ('Bernie Sanders Wearing Mittens Sitting in a Chair ', null, 400,
        'Bernie Sanders Wearing Mittens Sitting in a Chair refers to the numerous jokes and photoshops made from pictures of Vermont Senator Bernie Sanders'' attending the Inauguration of Joe Biden in a parka and mittens. In particular, a picture of Sanders sitting bundled up in a chair became an image macro and exploitable series.'),
       ('Stepping On The Beach', null, 500,
        'Stepping On The Beach refers to a song sung by SpongeBob in a scene from the SpongeBob SquarePants episode "Walking Small." The scene has been parodied numerous times in remixes with other songs.'),
       ('Ah Shit, Here We Go Again', null, 400,
        'Ah Shit, Here We Go Again refers to a memorable scene from 2004 action-adventure video game Grand Theft Auto: San Andreas. Starting in April 2019, the scene gained significant popularity as an exploitable, often used in reference to repeating confrontations, although other meanings can also be derived depending on the context.'),
       ('Daniel Radcliffe Holding Two Guns', null, 300,
        'Daniel Radcliffe Holding Two Guns refers to a series of image macros based on a photograph of actor Daniel Radcliffe wearing a bathrobe and holding two guns taken on the set for the film Guns Akimbo.'),
       ('Ladies and Gentlemen, We Got Him ', null, 200,
        '"Ladies and Gentlemen, We Got Him" is a quote originally uttered by American diplomat Paul Bremer during a 2003 press conference announcing the capture of Saddam Hussein. In 2018, the scene, coupled with audio from the Breakbot song "Baby I''m Yours", began to be widely used in various remixes on YouTube paired with clips of people being apprehended or caught off-guard in some fashion, often in the context of FBI operations or ligma jokes.'),
       ('Crying Cat', null, 100,
        'Crying Cat, also known as Schmuserkadser, refers to a series of photoshopped images of cats with teary, glassy eyes to appear as though they are sad. The earliest known usage of the Crying Cat was published by an anonymous Meme Generator user on June 11th, 2014. The image is a photoshopped version of Serious Cat, due to the fact that the background of the image and ears and color of the cat are identical.'),
       ('The Darkest Timeline', null, 200,
        'The Darkest Timeline is a reference to the multi-verse theory which hypothesizes that there are multiple universes outside of our own in which all things are possible, and that we live in the worst possible of these universes. After the phrase was popularized by an episode of Community, it became a popular reference online to discuss confusion at current events, although it has also been used as a snowclone to express different opinions at current events (i.e. "The Best Timeline," "The Strangest Timeline," etc.).'),
       ('Coffin Dance', null, 300,
        'Coffin Dance, also known as Dancing Pallbearers or Dancing Coffin, refers to several videos showing Ghanian pallbearers dancing while they are carrying a coffin. In March 2020, the videos, paired with EDM song "Astronomia" by Tony Igy, gained popularity in FAIL edits, similar to To Be Continued and We''ll Be Right Back memes. The first of the three most popular videos that gained popularity in connection with the trend was uploaded to YouTube by Travelin Sister on January 22nd, 2015 and depicted Ghana''s cultural phenomenon of dancing pallbearers'),
       ('Dramatic Dmitry', null, 400,
        'Dramatic Dmitry is a reaction image macro series featuring images from the album Paranoia by Russian musician Vladimir Brest. The meme includes several images of him expressing sadness on the beach. On the cover, he runs sand through his hands with intense focus; sits on his knees with his arms outstretched looking to the sky; and other positions showing despair. Online, many use the meme to express frustration over trivial or First World Problems'),
       ('All Right Then, Keep Your Secrets ', null, 500,
        '"All Right Then, Keep Your Secrets" is a memorable quote uttered by Frodo, the main protagonist of the fantasy franchise The Lord of the Rings, in the 2001 feature film The Lord of the Rings: The Fellowship of the Ring. Online, a screen capture of the moment Frodo saying the line has been used as a reaction image.'),
       ('James Franco “First Time?” ', null, 400,
        'James Franco "First time?" refers to a memorable quote by an unnamed cowboy character on the gallows in the 2018 western film The Ballad of Buster Scruggs, as portrayed by American actor James Franco. Since the film''s release in November 2018, a screen-captured image of the scene has been used in image macros as the punchline to jokes about one''s inexperience usually to emphasize an uncommon or ridiculous occurrence in normal society that has become a regular occurrence in a community.'),
       ('PogChamp', null, 500,
        'PogChamp, also known as Pog Champion or Play of Game Champ, is one of the oldest emotes on Twitch. The emote is used as a way to express excitement or surprise both genuinely or sarcastically. Typically PogChamp is spammed during a stream when something exciting happens, such as pulling off a clutch kill or play, but the emote can also be used in a trolling fashion where there is no hype, like a streamer failing a challenge or being killed in a mundane setting. In 2020, phrases PogChamp and its derivatives POGGERS and Pog gained significant presence in online slang, often used to express hype and other positive emotions.'),
       ('Stonks', null, 400,
        'Stonks is an intentional misspelling of the word "stocks" which is often associated with a surreal meme featuring the character Meme Man standing in front of a picture representing the stock market followed by the caption "Stonks." The picture began seeing use as a reaction image online in jokes about making poor financial decisions.'),
       ('Mini Keanu Reeves ', null, 300,
        'Mini Keanu Reeves, also known as Midget Keanu Reeves and Short Keanu Reeves, refers to a still image of Keanu Reeves from the E3 2019 Cyberpunk 2077 presentation, edited to make the actor appear disproportionately short. Online, the image has been circulated as a blursed image and used as an exploitable.'),
       ('Hey There Demons', null, 200,
        'Hey There Demons refers to a screenshot of an episode of Buzzfeed Unsolved: Supernatural in which a man addresses ghosts that may be in a room with "Hey there demons, it''s me, ya boy." The shot became a reaction image in jokes where a person casually addresses their mental problems.'),
       ('Slaps Chicken at 3275.95 MPH', null, 100,
        'Slaps Chicken at 3725.95 MPH refers to an idea that the heat generated by hitting a chicken with a hand at 3725.95 miles per hour, or 1665.65 m/s, would be enough to completely cook it. Using the conversion between kinetic energy and thermal energy, a Facebook user came up with the theory, leading to the creation of memes in various templates about it.');

/*TODO: When hashing has been implemented, replace all passwords with their hashed counterparts*/
insert into users(username, password, wallet)
VALUES ('Mori', 'y0urM0ri', 1200),
       ('Ruiner', 'g00dD0g', 800),
       ('MF DOOM', '0neB33r', 200),
       ('BT', 'B3tY0uD1dnt3xp3ctTh1s', 2500),
       ('Daemon', 'Test123', 300),
       ('Dockery', 'WhA1ing', 900),
       ('Same', 'Similar', 200),
       ('Same2', 'Similarity', 700),
       ('HomeStead', 'Fr3meW0rkFTW', 500),
       ('R3trofy', 'M0reInteresting', 600),
       ('Vagrant', 'Fa1ledF0rM3', 300);

insert into collections(user_id, card_id)
VALUES
    /*Creating collection for Mori*/
    (1, 2),
    (1, 2),
    (1, 2),
    (1, 3),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 7),
    (1, 1),
    (1, 10),
    /*Creating collection for Ruiner*/
    (2, 3),
    (2, 3),
    (2, 4),
    (2, 4),
    (2, 12),
    (2, 15),
    (2, 15),
    (2, 4),
    (2, 7),
    (2, 9),
    (2, 13),
    /*Creating collection for MF DOOM*/
    (3, 12),
    (3, 13),
    (3, 2),
    (3, 5),
    /*Creating collection for BT*/
    (4, 2),
    (4, 6),
    (4, 5),
    (4, 8),
    (4, 9),
    (4, 13),
    (4, 4),
    (4, 1),
    /*Creating collection for Daemon*/
    (5, 1),
    (5, 2),
    (5, 3),
    (5, 4),
    (5, 5),
    (5, 6),
    (5, 7),
    (5, 8),
    (5, 9),
    (5, 10),
    (5, 11),
    (5, 12),
    (5, 13),
    (5, 14),
    (5, 12),
    (5, 8),
    (5, 8),
    (5, 2),
    /*Creating collection for Dockery*/
    (6, 2),
    (6, 2),
    (6, 6),
    (6, 6),
    (6, 6),
    (6, 4),
    (6, 8),
    (6, 11),
    /*Creating collection for Same*/
    (7, 1),
    (7, 2),
    (7, 3),
    (7, 4),
    /*Creating collection for Same2*/
    (8, 1),
    (8, 2),
    (8, 3),
    (8, 4),
    /*Creating collection for Homestead*/
    (9, 1),
    /*Creating collection for Vagrant*/
    (11, 2),
    (11, 8),
    (11, 5);

insert into chats(participant_id_1, participant_id_2)
VALUES (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9),
       (1, 11),
       (2, 3),
       (2, 5),
       (2, 7),
       (2, 9),
       (3, 4),
       (3, 6),
       (3, 7),
       (4, 3),
       (4, 5),
       (4, 7),
       (5, 3);